/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ForPartnersRouteImport } from './routes/for-partners'
import { Route as GamePlansRouteImport } from './routes/game-plans'
import { Route as HqRouteImport } from './routes/hq'
import { Route as HuddleRouteImport } from './routes/huddle'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LockerRouteImport } from './routes/locker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskModelingRouteImport } from './routes/desk.modeling'
import { Route as HqIndexRouteImport } from './routes/hq.index'
import { Route as HqAccountRouteImport } from './routes/hq.account'
import { Route as HqAdminRouteImport } from './routes/hq.admin'
import { Route as HqAlertsRouteImport } from './routes/hq.alerts'
import { Route as HqBillingRouteImport } from './routes/hq.billing'
import { Route as HqDealsRouteImport } from './routes/hq.deals'
import { Route as HqDocumentsRouteImport } from './routes/hq.documents'
import { Route as HqEquipmentRouteImport } from './routes/hq.equipment'
import { Route as HqFieldReportRouteImport } from './routes/hq.field-report'
import { Route as HqFilesRouteImport } from './routes/hq.files'
import { Route as HqFilmRouteImport } from './routes/hq.film'
import { Route as HqHuddleRouteImport } from './routes/hq.huddle'
import { Route as HqLettersRouteImport } from './routes/hq.letters'
import { Route as HqMeetingsRouteImport } from './routes/hq.meetings'
import { Route as HqMembershipRouteImport } from './routes/hq.membership'
import { Route as HqMessagesRouteImport } from './routes/hq.messages'
import { Route as HqModelingRouteImport } from './routes/hq.modeling'
import { Route as HqOnboardingRouteImport } from './routes/hq.onboarding'
import { Route as HqPlaybookRouteImport } from './routes/hq.playbook'
import { Route as HqProjectsRouteImport } from './routes/hq.projects'
import { Route as HqVerifyRouteImport } from './routes/hq.verify'
import { Route as PlaybookIndexRouteImport } from './routes/playbook.index'
import { Route as PlaybookBuilderRouteImport } from './routes/playbook.builder'
import { Route as PlaybookHearingRouteImport } from './routes/playbook.hearing'
import { Route as PlaybookNeighborhoodRouteImport } from './routes/playbook.neighborhood'
import { Route as PlaybookOutreachRouteImport } from './routes/playbook.outreach'
import { Route as PlaybookPrivateIntroRouteImport } from './routes/playbook.private-intro'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsModelingRouteImport } from './routes/tools.modeling'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HqDealDealIdRouteImport } from './routes/hq.deal.$dealId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPartnersRoute = ForPartnersRouteImport.update({
  id: '/for-partners',
  path: '/for-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlansRoute = GamePlansRouteImport.update({
  id: '/game-plans',
  path: '/game-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const HuddleRoute = HuddleRouteImport.update({
  id: '/huddle',
  path: '/huddle',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerRoute = LockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskModelingRoute = DeskModelingRouteImport.update({
  id: '/modeling',
  path: '/modeling',
  getParentRoute: () => DeskRoute,
} as any)
const HqIndexRoute = HqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HqRoute,
} as any)
const HqAccountRoute = HqAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => HqRoute,
} as any)
const HqAdminRoute = HqAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => HqRoute,
} as any)
const HqAlertsRoute = HqAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => HqRoute,
} as any)
const HqBillingRoute = HqBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => HqRoute,
} as any)
const HqDealsRoute = HqDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => HqRoute,
} as any)
const HqDocumentsRoute = HqDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => HqRoute,
} as any)
const HqEquipmentRoute = HqEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => HqRoute,
} as any)
const HqFieldReportRoute = HqFieldReportRouteImport.update({
  id: '/field-report',
  path: '/field-report',
  getParentRoute: () => HqRoute,
} as any)
const HqFilesRoute = HqFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => HqRoute,
} as any)
const HqFilmRoute = HqFilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => HqRoute,
} as any)
const HqHuddleRoute = HqHuddleRouteImport.update({
  id: '/huddle',
  path: '/huddle',
  getParentRoute: () => HqRoute,
} as any)
const HqLettersRoute = HqLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => HqRoute,
} as any)
const HqMeetingsRoute = HqMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => HqRoute,
} as any)
const HqMembershipRoute = HqMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => HqRoute,
} as any)
const HqMessagesRoute = HqMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => HqRoute,
} as any)
const HqModelingRoute = HqModelingRouteImport.update({
  id: '/modeling',
  path: '/modeling',
  getParentRoute: () => HqRoute,
} as any)
const HqOnboardingRoute = HqOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => HqRoute,
} as any)
const HqPlaybookRoute = HqPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => HqRoute,
} as any)
const HqProjectsRoute = HqProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => HqRoute,
} as any)
const HqVerifyRoute = HqVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => HqRoute,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookBuilderRoute = PlaybookBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookHearingRoute = PlaybookHearingRouteImport.update({
  id: '/hearing',
  path: '/hearing',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookNeighborhoodRoute = PlaybookNeighborhoodRouteImport.update({
  id: '/neighborhood',
  path: '/neighborhood',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookOutreachRoute = PlaybookOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookPrivateIntroRoute = PlaybookPrivateIntroRouteImport.update({
  id: '/private-intro',
  path: '/private-intro',
  getParentRoute: () => PlaybookRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsModelingRoute = ToolsModelingRouteImport.update({
  id: '/modeling',
  path: '/modeling',
  getParentRoute: () => ToolsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HqDealDealIdRoute = HqDealDealIdRouteImport.update({
  id: '/deal/$dealId',
  path: '/deal/$dealId',
  getParentRoute: () => HqRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRouteWithChildren
  '/for-partners': typeof ForPartnersRoute
  '/game-plans': typeof GamePlansRoute
  '/hq': typeof HqRouteWithChildren
  '/huddle': typeof HuddleRoute
  '/inquiry': typeof InquiryRoute
  '/legal': typeof LegalRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/tools': typeof ToolsRouteWithChildren
  '/videos': typeof VideosRoute
  '/api/health': typeof ApiHealthRoute
  '/desk/modeling': typeof DeskModelingRoute
  '/hq/account': typeof HqAccountRoute
  '/hq/admin': typeof HqAdminRoute
  '/hq/alerts': typeof HqAlertsRoute
  '/hq/billing': typeof HqBillingRoute
  '/hq/deals': typeof HqDealsRoute
  '/hq/documents': typeof HqDocumentsRoute
  '/hq/equipment': typeof HqEquipmentRoute
  '/hq/field-report': typeof HqFieldReportRoute
  '/hq/files': typeof HqFilesRoute
  '/hq/film': typeof HqFilmRoute
  '/hq/huddle': typeof HqHuddleRoute
  '/hq/letters': typeof HqLettersRoute
  '/hq/meetings': typeof HqMeetingsRoute
  '/hq/membership': typeof HqMembershipRoute
  '/hq/messages': typeof HqMessagesRoute
  '/hq/modeling': typeof HqModelingRoute
  '/hq/onboarding': typeof HqOnboardingRoute
  '/hq/playbook': typeof HqPlaybookRoute
  '/hq/projects': typeof HqProjectsRoute
  '/hq/verify': typeof HqVerifyRoute
  '/playbook/builder': typeof PlaybookBuilderRoute
  '/playbook/hearing': typeof PlaybookHearingRoute
  '/playbook/neighborhood': typeof PlaybookNeighborhoodRoute
  '/playbook/outreach': typeof PlaybookOutreachRoute
  '/playbook/private-intro': typeof PlaybookPrivateIntroRoute
  '/tools/modeling': typeof ToolsModelingRoute
  '/desk/': typeof DeskIndexRoute
  '/hq/': typeof HqIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/hq/deal/$dealId': typeof HqDealDealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/for-partners': typeof ForPartnersRoute
  '/game-plans': typeof GamePlansRoute
  '/huddle': typeof HuddleRoute
  '/inquiry': typeof InquiryRoute
  '/legal': typeof LegalRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/videos': typeof VideosRoute
  '/api/health': typeof ApiHealthRoute
  '/desk/modeling': typeof DeskModelingRoute
  '/hq/account': typeof HqAccountRoute
  '/hq/admin': typeof HqAdminRoute
  '/hq/alerts': typeof HqAlertsRoute
  '/hq/billing': typeof HqBillingRoute
  '/hq/deals': typeof HqDealsRoute
  '/hq/documents': typeof HqDocumentsRoute
  '/hq/equipment': typeof HqEquipmentRoute
  '/hq/field-report': typeof HqFieldReportRoute
  '/hq/files': typeof HqFilesRoute
  '/hq/film': typeof HqFilmRoute
  '/hq/huddle': typeof HqHuddleRoute
  '/hq/letters': typeof HqLettersRoute
  '/hq/meetings': typeof HqMeetingsRoute
  '/hq/membership': typeof HqMembershipRoute
  '/hq/messages': typeof HqMessagesRoute
  '/hq/modeling': typeof HqModelingRoute
  '/hq/onboarding': typeof HqOnboardingRoute
  '/hq/playbook': typeof HqPlaybookRoute
  '/hq/projects': typeof HqProjectsRoute
  '/hq/verify': typeof HqVerifyRoute
  '/playbook/builder': typeof PlaybookBuilderRoute
  '/playbook/hearing': typeof PlaybookHearingRoute
  '/playbook/neighborhood': typeof PlaybookNeighborhoodRoute
  '/playbook/outreach': typeof PlaybookOutreachRoute
  '/playbook/private-intro': typeof PlaybookPrivateIntroRoute
  '/tools/modeling': typeof ToolsModelingRoute
  '/desk': typeof DeskIndexRoute
  '/hq': typeof HqIndexRoute
  '/playbook': typeof PlaybookIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/hq/deal/$dealId': typeof HqDealDealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRouteWithChildren
  '/for-partners': typeof ForPartnersRoute
  '/game-plans': typeof GamePlansRoute
  '/hq': typeof HqRouteWithChildren
  '/huddle': typeof HuddleRoute
  '/inquiry': typeof InquiryRoute
  '/legal': typeof LegalRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/tools': typeof ToolsRouteWithChildren
  '/videos': typeof VideosRoute
  '/api/health': typeof ApiHealthRoute
  '/desk/modeling': typeof DeskModelingRoute
  '/hq/account': typeof HqAccountRoute
  '/hq/admin': typeof HqAdminRoute
  '/hq/alerts': typeof HqAlertsRoute
  '/hq/billing': typeof HqBillingRoute
  '/hq/deals': typeof HqDealsRoute
  '/hq/documents': typeof HqDocumentsRoute
  '/hq/equipment': typeof HqEquipmentRoute
  '/hq/field-report': typeof HqFieldReportRoute
  '/hq/files': typeof HqFilesRoute
  '/hq/film': typeof HqFilmRoute
  '/hq/huddle': typeof HqHuddleRoute
  '/hq/letters': typeof HqLettersRoute
  '/hq/meetings': typeof HqMeetingsRoute
  '/hq/membership': typeof HqMembershipRoute
  '/hq/messages': typeof HqMessagesRoute
  '/hq/modeling': typeof HqModelingRoute
  '/hq/onboarding': typeof HqOnboardingRoute
  '/hq/playbook': typeof HqPlaybookRoute
  '/hq/projects': typeof HqProjectsRoute
  '/hq/verify': typeof HqVerifyRoute
  '/playbook/builder': typeof PlaybookBuilderRoute
  '/playbook/hearing': typeof PlaybookHearingRoute
  '/playbook/neighborhood': typeof PlaybookNeighborhoodRoute
  '/playbook/outreach': typeof PlaybookOutreachRoute
  '/playbook/private-intro': typeof PlaybookPrivateIntroRoute
  '/tools/modeling': typeof ToolsModelingRoute
  '/desk/': typeof DeskIndexRoute
  '/hq/': typeof HqIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/hq/deal/$dealId': typeof HqDealDealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/access'
    | '/advisory'
    | '/contact'
    | '/desk'
    | '/for-partners'
    | '/game-plans'
    | '/hq'
    | '/huddle'
    | '/inquiry'
    | '/legal'
    | '/locker'
    | '/login'
    | '/playbook'
    | '/pricing'
    | '/register'
    | '/tools'
    | '/videos'
    | '/api/health'
    | '/desk/modeling'
    | '/hq/account'
    | '/hq/admin'
    | '/hq/alerts'
    | '/hq/billing'
    | '/hq/deals'
    | '/hq/documents'
    | '/hq/equipment'
    | '/hq/field-report'
    | '/hq/files'
    | '/hq/film'
    | '/hq/huddle'
    | '/hq/letters'
    | '/hq/meetings'
    | '/hq/membership'
    | '/hq/messages'
    | '/hq/modeling'
    | '/hq/onboarding'
    | '/hq/playbook'
    | '/hq/projects'
    | '/hq/verify'
    | '/playbook/builder'
    | '/playbook/hearing'
    | '/playbook/neighborhood'
    | '/playbook/outreach'
    | '/playbook/private-intro'
    | '/tools/modeling'
    | '/desk/'
    | '/hq/'
    | '/playbook/'
    | '/tools/'
    | '/api/auth/$'
    | '/hq/deal/$dealId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/access'
    | '/advisory'
    | '/contact'
    | '/for-partners'
    | '/game-plans'
    | '/huddle'
    | '/inquiry'
    | '/legal'
    | '/locker'
    | '/login'
    | '/pricing'
    | '/register'
    | '/videos'
    | '/api/health'
    | '/desk/modeling'
    | '/hq/account'
    | '/hq/admin'
    | '/hq/alerts'
    | '/hq/billing'
    | '/hq/deals'
    | '/hq/documents'
    | '/hq/equipment'
    | '/hq/field-report'
    | '/hq/files'
    | '/hq/film'
    | '/hq/huddle'
    | '/hq/letters'
    | '/hq/meetings'
    | '/hq/membership'
    | '/hq/messages'
    | '/hq/modeling'
    | '/hq/onboarding'
    | '/hq/playbook'
    | '/hq/projects'
    | '/hq/verify'
    | '/playbook/builder'
    | '/playbook/hearing'
    | '/playbook/neighborhood'
    | '/playbook/outreach'
    | '/playbook/private-intro'
    | '/tools/modeling'
    | '/desk'
    | '/hq'
    | '/playbook'
    | '/tools'
    | '/api/auth/$'
    | '/hq/deal/$dealId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/access'
    | '/advisory'
    | '/contact'
    | '/desk'
    | '/for-partners'
    | '/game-plans'
    | '/hq'
    | '/huddle'
    | '/inquiry'
    | '/legal'
    | '/locker'
    | '/login'
    | '/playbook'
    | '/pricing'
    | '/register'
    | '/tools'
    | '/videos'
    | '/api/health'
    | '/desk/modeling'
    | '/hq/account'
    | '/hq/admin'
    | '/hq/alerts'
    | '/hq/billing'
    | '/hq/deals'
    | '/hq/documents'
    | '/hq/equipment'
    | '/hq/field-report'
    | '/hq/files'
    | '/hq/film'
    | '/hq/huddle'
    | '/hq/letters'
    | '/hq/meetings'
    | '/hq/membership'
    | '/hq/messages'
    | '/hq/modeling'
    | '/hq/onboarding'
    | '/hq/playbook'
    | '/hq/projects'
    | '/hq/verify'
    | '/playbook/builder'
    | '/playbook/hearing'
    | '/playbook/neighborhood'
    | '/playbook/outreach'
    | '/playbook/private-intro'
    | '/tools/modeling'
    | '/desk/'
    | '/hq/'
    | '/playbook/'
    | '/tools/'
    | '/api/auth/$'
    | '/hq/deal/$dealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessRoute: typeof AccessRoute
  AdvisoryRoute: typeof AdvisoryRoute
  ContactRoute: typeof ContactRoute
  DeskRoute: typeof DeskRouteWithChildren
  ForPartnersRoute: typeof ForPartnersRoute
  GamePlansRoute: typeof GamePlansRoute
  HqRoute: typeof HqRouteWithChildren
  HuddleRoute: typeof HuddleRoute
  InquiryRoute: typeof InquiryRoute
  LegalRoute: typeof LegalRoute
  LockerRoute: typeof LockerRoute
  LoginRoute: typeof LoginRoute
  PlaybookRoute: typeof PlaybookRouteWithChildren
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  VideosRoute: typeof VideosRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-partners': {
      id: '/for-partners'
      path: '/for-partners'
      fullPath: '/for-partners'
      preLoaderRoute: typeof ForPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-plans': {
      id: '/game-plans'
      path: '/game-plans'
      fullPath: '/game-plans'
      preLoaderRoute: typeof GamePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huddle': {
      id: '/huddle'
      path: '/huddle'
      fullPath: '/huddle'
      preLoaderRoute: typeof HuddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker': {
      id: '/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof LockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/modeling': {
      id: '/desk/modeling'
      path: '/modeling'
      fullPath: '/desk/modeling'
      preLoaderRoute: typeof DeskModelingRouteImport
      parentRoute: typeof DeskRoute
    }
    '/hq/': {
      id: '/hq/'
      path: '/'
      fullPath: '/hq/'
      preLoaderRoute: typeof HqIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/account': {
      id: '/hq/account'
      path: '/account'
      fullPath: '/hq/account'
      preLoaderRoute: typeof HqAccountRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/admin': {
      id: '/hq/admin'
      path: '/admin'
      fullPath: '/hq/admin'
      preLoaderRoute: typeof HqAdminRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/alerts': {
      id: '/hq/alerts'
      path: '/alerts'
      fullPath: '/hq/alerts'
      preLoaderRoute: typeof HqAlertsRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/billing': {
      id: '/hq/billing'
      path: '/billing'
      fullPath: '/hq/billing'
      preLoaderRoute: typeof HqBillingRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/deals': {
      id: '/hq/deals'
      path: '/deals'
      fullPath: '/hq/deals'
      preLoaderRoute: typeof HqDealsRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/documents': {
      id: '/hq/documents'
      path: '/documents'
      fullPath: '/hq/documents'
      preLoaderRoute: typeof HqDocumentsRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/equipment': {
      id: '/hq/equipment'
      path: '/equipment'
      fullPath: '/hq/equipment'
      preLoaderRoute: typeof HqEquipmentRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/field-report': {
      id: '/hq/field-report'
      path: '/field-report'
      fullPath: '/hq/field-report'
      preLoaderRoute: typeof HqFieldReportRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/files': {
      id: '/hq/files'
      path: '/files'
      fullPath: '/hq/files'
      preLoaderRoute: typeof HqFilesRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/film': {
      id: '/hq/film'
      path: '/film'
      fullPath: '/hq/film'
      preLoaderRoute: typeof HqFilmRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/huddle': {
      id: '/hq/huddle'
      path: '/huddle'
      fullPath: '/hq/huddle'
      preLoaderRoute: typeof HqHuddleRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/letters': {
      id: '/hq/letters'
      path: '/letters'
      fullPath: '/hq/letters'
      preLoaderRoute: typeof HqLettersRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/meetings': {
      id: '/hq/meetings'
      path: '/meetings'
      fullPath: '/hq/meetings'
      preLoaderRoute: typeof HqMeetingsRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/membership': {
      id: '/hq/membership'
      path: '/membership'
      fullPath: '/hq/membership'
      preLoaderRoute: typeof HqMembershipRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/messages': {
      id: '/hq/messages'
      path: '/messages'
      fullPath: '/hq/messages'
      preLoaderRoute: typeof HqMessagesRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/modeling': {
      id: '/hq/modeling'
      path: '/modeling'
      fullPath: '/hq/modeling'
      preLoaderRoute: typeof HqModelingRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/onboarding': {
      id: '/hq/onboarding'
      path: '/onboarding'
      fullPath: '/hq/onboarding'
      preLoaderRoute: typeof HqOnboardingRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/playbook': {
      id: '/hq/playbook'
      path: '/playbook'
      fullPath: '/hq/playbook'
      preLoaderRoute: typeof HqPlaybookRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/projects': {
      id: '/hq/projects'
      path: '/projects'
      fullPath: '/hq/projects'
      preLoaderRoute: typeof HqProjectsRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/verify': {
      id: '/hq/verify'
      path: '/verify'
      fullPath: '/hq/verify'
      preLoaderRoute: typeof HqVerifyRouteImport
      parentRoute: typeof HqRoute
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/builder': {
      id: '/playbook/builder'
      path: '/builder'
      fullPath: '/playbook/builder'
      preLoaderRoute: typeof PlaybookBuilderRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/hearing': {
      id: '/playbook/hearing'
      path: '/hearing'
      fullPath: '/playbook/hearing'
      preLoaderRoute: typeof PlaybookHearingRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/neighborhood': {
      id: '/playbook/neighborhood'
      path: '/neighborhood'
      fullPath: '/playbook/neighborhood'
      preLoaderRoute: typeof PlaybookNeighborhoodRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/outreach': {
      id: '/playbook/outreach'
      path: '/outreach'
      fullPath: '/playbook/outreach'
      preLoaderRoute: typeof PlaybookOutreachRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/private-intro': {
      id: '/playbook/private-intro'
      path: '/private-intro'
      fullPath: '/playbook/private-intro'
      preLoaderRoute: typeof PlaybookPrivateIntroRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/modeling': {
      id: '/tools/modeling'
      path: '/modeling'
      fullPath: '/tools/modeling'
      preLoaderRoute: typeof ToolsModelingRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/deal/$dealId': {
      id: '/hq/deal/$dealId'
      path: '/deal/$dealId'
      fullPath: '/hq/deal/$dealId'
      preLoaderRoute: typeof HqDealDealIdRouteImport
      parentRoute: typeof HqRoute
    }
  }
}

interface DeskRouteChildren {
  DeskModelingRoute: typeof DeskModelingRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskModelingRoute: DeskModelingRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface HqRouteChildren {
  HqAccountRoute: typeof HqAccountRoute
  HqAdminRoute: typeof HqAdminRoute
  HqAlertsRoute: typeof HqAlertsRoute
  HqBillingRoute: typeof HqBillingRoute
  HqDealsRoute: typeof HqDealsRoute
  HqDocumentsRoute: typeof HqDocumentsRoute
  HqEquipmentRoute: typeof HqEquipmentRoute
  HqFieldReportRoute: typeof HqFieldReportRoute
  HqFilesRoute: typeof HqFilesRoute
  HqFilmRoute: typeof HqFilmRoute
  HqHuddleRoute: typeof HqHuddleRoute
  HqLettersRoute: typeof HqLettersRoute
  HqMeetingsRoute: typeof HqMeetingsRoute
  HqMembershipRoute: typeof HqMembershipRoute
  HqMessagesRoute: typeof HqMessagesRoute
  HqModelingRoute: typeof HqModelingRoute
  HqOnboardingRoute: typeof HqOnboardingRoute
  HqPlaybookRoute: typeof HqPlaybookRoute
  HqProjectsRoute: typeof HqProjectsRoute
  HqVerifyRoute: typeof HqVerifyRoute
  HqIndexRoute: typeof HqIndexRoute
  HqDealDealIdRoute: typeof HqDealDealIdRoute
}

const HqRouteChildren: HqRouteChildren = {
  HqAccountRoute: HqAccountRoute,
  HqAdminRoute: HqAdminRoute,
  HqAlertsRoute: HqAlertsRoute,
  HqBillingRoute: HqBillingRoute,
  HqDealsRoute: HqDealsRoute,
  HqDocumentsRoute: HqDocumentsRoute,
  HqEquipmentRoute: HqEquipmentRoute,
  HqFieldReportRoute: HqFieldReportRoute,
  HqFilesRoute: HqFilesRoute,
  HqFilmRoute: HqFilmRoute,
  HqHuddleRoute: HqHuddleRoute,
  HqLettersRoute: HqLettersRoute,
  HqMeetingsRoute: HqMeetingsRoute,
  HqMembershipRoute: HqMembershipRoute,
  HqMessagesRoute: HqMessagesRoute,
  HqModelingRoute: HqModelingRoute,
  HqOnboardingRoute: HqOnboardingRoute,
  HqPlaybookRoute: HqPlaybookRoute,
  HqProjectsRoute: HqProjectsRoute,
  HqVerifyRoute: HqVerifyRoute,
  HqIndexRoute: HqIndexRoute,
  HqDealDealIdRoute: HqDealDealIdRoute,
}

const HqRouteWithChildren = HqRoute._addFileChildren(HqRouteChildren)

interface PlaybookRouteChildren {
  PlaybookBuilderRoute: typeof PlaybookBuilderRoute
  PlaybookHearingRoute: typeof PlaybookHearingRoute
  PlaybookNeighborhoodRoute: typeof PlaybookNeighborhoodRoute
  PlaybookOutreachRoute: typeof PlaybookOutreachRoute
  PlaybookPrivateIntroRoute: typeof PlaybookPrivateIntroRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
}

const PlaybookRouteChildren: PlaybookRouteChildren = {
  PlaybookBuilderRoute: PlaybookBuilderRoute,
  PlaybookHearingRoute: PlaybookHearingRoute,
  PlaybookNeighborhoodRoute: PlaybookNeighborhoodRoute,
  PlaybookOutreachRoute: PlaybookOutreachRoute,
  PlaybookPrivateIntroRoute: PlaybookPrivateIntroRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
}

const PlaybookRouteWithChildren = PlaybookRoute._addFileChildren(
  PlaybookRouteChildren,
)

interface ToolsRouteChildren {
  ToolsModelingRoute: typeof ToolsModelingRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsModelingRoute: ToolsModelingRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessRoute: AccessRoute,
  AdvisoryRoute: AdvisoryRoute,
  ContactRoute: ContactRoute,
  DeskRoute: DeskRouteWithChildren,
  ForPartnersRoute: ForPartnersRoute,
  GamePlansRoute: GamePlansRoute,
  HqRoute: HqRouteWithChildren,
  HuddleRoute: HuddleRoute,
  InquiryRoute: InquiryRoute,
  LegalRoute: LegalRoute,
  LockerRoute: LockerRoute,
  LoginRoute: LoginRoute,
  PlaybookRoute: PlaybookRouteWithChildren,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ToolsRoute: ToolsRouteWithChildren,
  VideosRoute: VideosRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
