/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ForPartnersRouteImport } from './routes/for-partners'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskModelingRouteImport } from './routes/desk.modeling'
import { Route as PlaybookIndexRouteImport } from './routes/playbook.index'
import { Route as PlaybookHearingRouteImport } from './routes/playbook.hearing'
import { Route as PlaybookNeighborhoodRouteImport } from './routes/playbook.neighborhood'
import { Route as PlaybookPrivateIntroRouteImport } from './routes/playbook.private-intro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPartnersRoute = ForPartnersRouteImport.update({
  id: '/for-partners',
  path: '/for-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskModelingRoute = DeskModelingRouteImport.update({
  id: '/modeling',
  path: '/modeling',
  getParentRoute: () => DeskRoute,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookHearingRoute = PlaybookHearingRouteImport.update({
  id: '/hearing',
  path: '/hearing',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookNeighborhoodRoute = PlaybookNeighborhoodRouteImport.update({
  id: '/neighborhood',
  path: '/neighborhood',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookPrivateIntroRoute = PlaybookPrivateIntroRouteImport.update({
  id: '/private-intro',
  path: '/private-intro',
  getParentRoute: () => PlaybookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRouteWithChildren
  '/for-partners': typeof ForPartnersRoute
  '/inquiry': typeof InquiryRoute
  '/legal': typeof LegalRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/videos': typeof VideosRoute
  '/desk/modeling': typeof DeskModelingRoute
  '/playbook/hearing': typeof PlaybookHearingRoute
  '/playbook/neighborhood': typeof PlaybookNeighborhoodRoute
  '/playbook/private-intro': typeof PlaybookPrivateIntroRoute
  '/desk/': typeof DeskIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/for-partners': typeof ForPartnersRoute
  '/inquiry': typeof InquiryRoute
  '/legal': typeof LegalRoute
  '/videos': typeof VideosRoute
  '/desk/modeling': typeof DeskModelingRoute
  '/playbook/hearing': typeof PlaybookHearingRoute
  '/playbook/neighborhood': typeof PlaybookNeighborhoodRoute
  '/playbook/private-intro': typeof PlaybookPrivateIntroRoute
  '/desk': typeof DeskIndexRoute
  '/playbook': typeof PlaybookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/advisory': typeof AdvisoryRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRouteWithChildren
  '/for-partners': typeof ForPartnersRoute
  '/inquiry': typeof InquiryRoute
  '/legal': typeof LegalRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/videos': typeof VideosRoute
  '/desk/modeling': typeof DeskModelingRoute
  '/playbook/hearing': typeof PlaybookHearingRoute
  '/playbook/neighborhood': typeof PlaybookNeighborhoodRoute
  '/playbook/private-intro': typeof PlaybookPrivateIntroRoute
  '/desk/': typeof DeskIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/access'
    | '/advisory'
    | '/contact'
    | '/desk'
    | '/for-partners'
    | '/inquiry'
    | '/legal'
    | '/playbook'
    | '/videos'
    | '/desk/modeling'
    | '/playbook/hearing'
    | '/playbook/neighborhood'
    | '/playbook/private-intro'
    | '/desk/'
    | '/playbook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/access'
    | '/advisory'
    | '/contact'
    | '/for-partners'
    | '/inquiry'
    | '/legal'
    | '/videos'
    | '/desk/modeling'
    | '/playbook/hearing'
    | '/playbook/neighborhood'
    | '/playbook/private-intro'
    | '/desk'
    | '/playbook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/access'
    | '/advisory'
    | '/contact'
    | '/desk'
    | '/for-partners'
    | '/inquiry'
    | '/legal'
    | '/playbook'
    | '/videos'
    | '/desk/modeling'
    | '/playbook/hearing'
    | '/playbook/neighborhood'
    | '/playbook/private-intro'
    | '/desk/'
    | '/playbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessRoute: typeof AccessRoute
  AdvisoryRoute: typeof AdvisoryRoute
  ContactRoute: typeof ContactRoute
  DeskRoute: typeof DeskRouteWithChildren
  ForPartnersRoute: typeof ForPartnersRoute
  InquiryRoute: typeof InquiryRoute
  LegalRoute: typeof LegalRoute
  PlaybookRoute: typeof PlaybookRouteWithChildren
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-partners': {
      id: '/for-partners'
      path: '/for-partners'
      fullPath: '/for-partners'
      preLoaderRoute: typeof ForPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/modeling': {
      id: '/desk/modeling'
      path: '/modeling'
      fullPath: '/desk/modeling'
      preLoaderRoute: typeof DeskModelingRouteImport
      parentRoute: typeof DeskRoute
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/hearing': {
      id: '/playbook/hearing'
      path: '/hearing'
      fullPath: '/playbook/hearing'
      preLoaderRoute: typeof PlaybookHearingRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/neighborhood': {
      id: '/playbook/neighborhood'
      path: '/neighborhood'
      fullPath: '/playbook/neighborhood'
      preLoaderRoute: typeof PlaybookNeighborhoodRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/private-intro': {
      id: '/playbook/private-intro'
      path: '/private-intro'
      fullPath: '/playbook/private-intro'
      preLoaderRoute: typeof PlaybookPrivateIntroRouteImport
      parentRoute: typeof PlaybookRoute
    }
  }
}

interface DeskRouteChildren {
  DeskModelingRoute: typeof DeskModelingRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskModelingRoute: DeskModelingRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface PlaybookRouteChildren {
  PlaybookHearingRoute: typeof PlaybookHearingRoute
  PlaybookNeighborhoodRoute: typeof PlaybookNeighborhoodRoute
  PlaybookPrivateIntroRoute: typeof PlaybookPrivateIntroRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
}

const PlaybookRouteChildren: PlaybookRouteChildren = {
  PlaybookHearingRoute: PlaybookHearingRoute,
  PlaybookNeighborhoodRoute: PlaybookNeighborhoodRoute,
  PlaybookPrivateIntroRoute: PlaybookPrivateIntroRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
}

const PlaybookRouteWithChildren = PlaybookRoute._addFileChildren(
  PlaybookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessRoute: AccessRoute,
  AdvisoryRoute: AdvisoryRoute,
  ContactRoute: ContactRoute,
  DeskRoute: DeskRouteWithChildren,
  ForPartnersRoute: ForPartnersRoute,
  InquiryRoute: InquiryRoute,
  LegalRoute: LegalRoute,
  PlaybookRoute: PlaybookRouteWithChildren,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
